services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=pgvectordb'
      - 'POSTGRES_PASSWORD=lucianopg'
      - 'POSTGRES_USER=lucianopg'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'
